/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "authenticationFlowType": 'USER_PASSWORD_AUTH',
    "aws_user_pools_id": "eu-west-1_ltlfeJ4DS",
    "aws_user_pools_web_client_id": "aws:cognito-idp:eu-west-1:303303306861:userpool/eu-west-1_ltlfeJ4DS"
};


export default awsmobile;

